# Generated by Django 3.1.3 on 2020-11-23 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='range',
        ),
        migrations.AddField(
            model_name='alert',
            name='severity',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=1),
        ),
    ]
