# Generated by Django 3.1.3 on 2020-11-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201123_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notif_id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('brief_description', models.TextField()),
                ('date_reported', models.DateTimeField(auto_now=True)),
                ('long', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('linked_article_url', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='alert',
            name='id',
        ),
        migrations.RemoveField(
            model_name='citizen',
            name='id',
        ),
        migrations.AddField(
            model_name='alert',
            name='alert_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='citizen',
            name='citizen_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
