# Generated by Django 3.1.3 on 2020-11-26 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20201125_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='sender_id',
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.citizen'),
        ),
    ]
