# Generated by Django 3.1.3 on 2020-11-26 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20201125_2217'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
